### ISSUE TITLE
Указать версию node в README и package.json

### ISSUE THREAD

**Issue by nkabardin** [linkasu/linka.looks-electron#32]
Установить не получается, в зависимости от разных версий ноды, yarn выдает ошибки либо.

например, на текущей LTS node 18.17.1:
```error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.17.1"```

Получается для проекта нужно указать требуемую версию ноды? Плюс, возможно, указать engines в package.json

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

**Comment by nkabardin** [comment]
Установить удалось только с версией ноды `v16.20.2`

**Comment by AgiosAndreas** [comment]
Могу поправить зависимости, чтобы собиралось на 18 версии node.
